@insurance_HostAddress = http://localhost:5270

GET {{insurance_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{insurance_HostAddress}}/login
Content-Type: application/json

{
  "Username":"admin",
  "Password":"123"
}
###
POST {{WebApi3_HostAddress}}/login
Content-Type: application/json

{
  "username":"admin",
  "password":"123"
}

###
GET {{insurance_HostAddress}}/UserList

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU1NjExNDksImlzcyI6Ikluc3VyYW5jZS5jb20iLCJhdWQiOiJJbnN1cmFuY2UuY29tIn0.V5r76aQkC8yd1ROgHxGEWVWDsl6ua8_ShqFyqiQ3CrE

### 
GET {{insurance_HostAddress}}/customerHome
Authorization: Bearer eyJhbGfgiOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU1NjA0MTEsImlzcyI6Ikluc3VyYW5jZS5jb20iLCJhdWQiOiJJbnN1cmFuY2UuY29tIn0.Y1wC6_dgSQlrXfc6cvVFDqLUShnxbMLjWmJN6zpSlao